
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "BasicServiceUsed" )
    public class BasicServiceUsed implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "BasicServiceUsed" , isSet = false )
       public static class BasicServiceUsedSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "basicService", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private BasicService basicService = null;
                
  
        @ASN1Element ( name = "chargingTimeStamp", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargingTimeStamp chargingTimeStamp = null;
                
  
        @ASN1Element ( name = "chargeInformationList", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargeInformationList chargeInformationList = null;
                
  
        @ASN1Element ( name = "dataVolumeReference", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DataVolumeReference dataVolumeReference = null;
                
  
        @ASN1Element ( name = "hSCSDInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private HSCSDInformation hSCSDInformation = null;
                
  
        
        public BasicService getBasicService () {
            return this.basicService;
        }

        
        public boolean isBasicServicePresent () {
            return this.basicService != null;
        }
        

        public void setBasicService (BasicService value) {
            this.basicService = value;
        }
        
  
        
        public ChargingTimeStamp getChargingTimeStamp () {
            return this.chargingTimeStamp;
        }

        
        public boolean isChargingTimeStampPresent () {
            return this.chargingTimeStamp != null;
        }
        

        public void setChargingTimeStamp (ChargingTimeStamp value) {
            this.chargingTimeStamp = value;
        }
        
  
        
        public ChargeInformationList getChargeInformationList () {
            return this.chargeInformationList;
        }

        
        public boolean isChargeInformationListPresent () {
            return this.chargeInformationList != null;
        }
        

        public void setChargeInformationList (ChargeInformationList value) {
            this.chargeInformationList = value;
        }
        
  
        
        public DataVolumeReference getDataVolumeReference () {
            return this.dataVolumeReference;
        }

        
        public boolean isDataVolumeReferencePresent () {
            return this.dataVolumeReference != null;
        }
        

        public void setDataVolumeReference (DataVolumeReference value) {
            this.dataVolumeReference = value;
        }
        
  
        
        public HSCSDInformation getHSCSDInformation () {
            return this.hSCSDInformation;
        }

        
        public boolean isHSCSDInformationPresent () {
            return this.hSCSDInformation != null;
        }
        

        public void setHSCSDInformation (HSCSDInformation value) {
            this.hSCSDInformation = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_BasicServiceUsedSequenceType;
        }

       private static IASN1PreparedElementData preparedData_BasicServiceUsedSequenceType = CoderFactory.getInstance().newPreparedElementData(BasicServiceUsedSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "BasicServiceUsed", isOptional =  false , hasTag =  true, tag = 39, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private BasicServiceUsedSequenceType  value;        

        
        
        public BasicServiceUsed () {
        }
        
        
        
        public void setValue(BasicServiceUsedSequenceType value) {
            this.value = value;
        }
        
        
        
        public BasicServiceUsedSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(BasicServiceUsed.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            