
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "CallOriginator" )
    public class CallOriginator implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "CallOriginator" , isSet = false )
       public static class CallOriginatorSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "callingNumber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private AddressStringDigits callingNumber = null;
                
  
        @ASN1Element ( name = "clirIndicator", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ClirIndicator clirIndicator = null;
                
  
        
        public AddressStringDigits getCallingNumber () {
            return this.callingNumber;
        }

        
        public boolean isCallingNumberPresent () {
            return this.callingNumber != null;
        }
        

        public void setCallingNumber (AddressStringDigits value) {
            this.callingNumber = value;
        }
        
  
        
        public ClirIndicator getClirIndicator () {
            return this.clirIndicator;
        }

        
        public boolean isClirIndicatorPresent () {
            return this.clirIndicator != null;
        }
        

        public void setClirIndicator (ClirIndicator value) {
            this.clirIndicator = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_CallOriginatorSequenceType;
        }

       private static IASN1PreparedElementData preparedData_CallOriginatorSequenceType = CoderFactory.getInstance().newPreparedElementData(CallOriginatorSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "CallOriginator", isOptional =  false , hasTag =  true, tag = 41, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private CallOriginatorSequenceType  value;        

        
        
        public CallOriginator () {
        }
        
        
        
        public void setValue(CallOriginatorSequenceType value) {
            this.value = value;
        }
        
        
        
        public CallOriginatorSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CallOriginator.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            