
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "CamelCallReference" )
    public class CamelCallReference implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "CamelCallReference" , isSet = false )
       public static class CamelCallReferenceSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "mscAddress", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private AddressStringDigits mscAddress = null;
                
  
        @ASN1Element ( name = "callReferenceNumber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CamelCallReferenceNumber callReferenceNumber = null;
                
  
        
        public AddressStringDigits getMscAddress () {
            return this.mscAddress;
        }

        
        public boolean isMscAddressPresent () {
            return this.mscAddress != null;
        }
        

        public void setMscAddress (AddressStringDigits value) {
            this.mscAddress = value;
        }
        
  
        
        public CamelCallReferenceNumber getCallReferenceNumber () {
            return this.callReferenceNumber;
        }

        
        public boolean isCallReferenceNumberPresent () {
            return this.callReferenceNumber != null;
        }
        

        public void setCallReferenceNumber (CamelCallReferenceNumber value) {
            this.callReferenceNumber = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_CamelCallReferenceSequenceType;
        }

       private static IASN1PreparedElementData preparedData_CamelCallReferenceSequenceType = CoderFactory.getInstance().newPreparedElementData(CamelCallReferenceSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "CamelCallReference", isOptional =  false , hasTag =  true, tag = 49, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private CamelCallReferenceSequenceType  value;        

        
        
        public CamelCallReference () {
        }
        
        
        
        public void setValue(CamelCallReferenceSequenceType value) {
            this.value = value;
        }
        
        
        
        public CamelCallReferenceSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CamelCallReference.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            