
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ChargedPartyIdentification" )
    public class ChargedPartyIdentification implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ChargedPartyIdentification" , isSet = false )
       public static class ChargedPartyIdentificationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "chargedPartyIdType", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargedPartyIdType chargedPartyIdType = null;
                
  
        @ASN1Element ( name = "chargedPartyIdentifier", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargedPartyIdentifier chargedPartyIdentifier = null;
                
  
        
        public ChargedPartyIdType getChargedPartyIdType () {
            return this.chargedPartyIdType;
        }

        
        public boolean isChargedPartyIdTypePresent () {
            return this.chargedPartyIdType != null;
        }
        

        public void setChargedPartyIdType (ChargedPartyIdType value) {
            this.chargedPartyIdType = value;
        }
        
  
        
        public ChargedPartyIdentifier getChargedPartyIdentifier () {
            return this.chargedPartyIdentifier;
        }

        
        public boolean isChargedPartyIdentifierPresent () {
            return this.chargedPartyIdentifier != null;
        }
        

        public void setChargedPartyIdentifier (ChargedPartyIdentifier value) {
            this.chargedPartyIdentifier = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ChargedPartyIdentificationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ChargedPartyIdentificationSequenceType = CoderFactory.getInstance().newPreparedElementData(ChargedPartyIdentificationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ChargedPartyIdentification", isOptional =  false , hasTag =  true, tag = 309, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ChargedPartyIdentificationSequenceType  value;        

        
        
        public ChargedPartyIdentification () {
        }
        
        
        
        public void setValue(ChargedPartyIdentificationSequenceType value) {
            this.value = value;
        }
        
        
        
        public ChargedPartyIdentificationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ChargedPartyIdentification.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            