
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "CurrencyConversionList" )
    public class CurrencyConversionList implements IASN1PreparedElement {
                
        
@ASN1SequenceOf( name = "CurrencyConversionList", isSetOf = false ) 

    
        @ASN1Element ( name = "CurrencyConversionList", isOptional =  false , hasTag =  true, tag = 80, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private java.util.Collection<CurrencyConversion>   value;        

        
        
        public CurrencyConversionList () {
        }
        
        
        
        public void setValue(java.util.Collection<CurrencyConversion>  value) {
            this.value = value;
        }
        
        
        
        public java.util.Collection<CurrencyConversion>  getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CurrencyConversionList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            