
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "GprsCall" )
    public class GprsCall implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "GprsCall" , isSet = false )
       public static class GprsCallSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "typeOfControllingNode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TypeOfControllingNode typeOfControllingNode = null;
                
  
        @ASN1Element ( name = "gprsBasicCallInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GprsBasicCallInformation gprsBasicCallInformation = null;
                
  
        @ASN1Element ( name = "gprsLocationInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GprsLocationInformation gprsLocationInformation = null;
                
  
        @ASN1Element ( name = "equipmentInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private EquipmentInformation equipmentInformation = null;
                
  
        @ASN1Element ( name = "gprsServiceUsed", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GprsServiceUsed gprsServiceUsed = null;
                
  
        @ASN1Element ( name = "camelServiceUsed", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CamelServiceUsed camelServiceUsed = null;
                
  
        @ASN1Element ( name = "valueAddedServiceUsedList", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ValueAddedServiceUsedList valueAddedServiceUsedList = null;
                
  
        @ASN1Element ( name = "operatorSpecInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private OperatorSpecInfoList operatorSpecInformation = null;
                
  
        
        public TypeOfControllingNode getTypeOfControllingNode () {
            return this.typeOfControllingNode;
        }

        
        public boolean isTypeOfControllingNodePresent () {
            return this.typeOfControllingNode != null;
        }
        

        public void setTypeOfControllingNode (TypeOfControllingNode value) {
            this.typeOfControllingNode = value;
        }
        
  
        
        public GprsBasicCallInformation getGprsBasicCallInformation () {
            return this.gprsBasicCallInformation;
        }

        
        public boolean isGprsBasicCallInformationPresent () {
            return this.gprsBasicCallInformation != null;
        }
        

        public void setGprsBasicCallInformation (GprsBasicCallInformation value) {
            this.gprsBasicCallInformation = value;
        }
        
  
        
        public GprsLocationInformation getGprsLocationInformation () {
            return this.gprsLocationInformation;
        }

        
        public boolean isGprsLocationInformationPresent () {
            return this.gprsLocationInformation != null;
        }
        

        public void setGprsLocationInformation (GprsLocationInformation value) {
            this.gprsLocationInformation = value;
        }
        
  
        
        public EquipmentInformation getEquipmentInformation () {
            return this.equipmentInformation;
        }

        
        public boolean isEquipmentInformationPresent () {
            return this.equipmentInformation != null;
        }
        

        public void setEquipmentInformation (EquipmentInformation value) {
            this.equipmentInformation = value;
        }
        
  
        
        public GprsServiceUsed getGprsServiceUsed () {
            return this.gprsServiceUsed;
        }

        
        public boolean isGprsServiceUsedPresent () {
            return this.gprsServiceUsed != null;
        }
        

        public void setGprsServiceUsed (GprsServiceUsed value) {
            this.gprsServiceUsed = value;
        }
        
  
        
        public CamelServiceUsed getCamelServiceUsed () {
            return this.camelServiceUsed;
        }

        
        public boolean isCamelServiceUsedPresent () {
            return this.camelServiceUsed != null;
        }
        

        public void setCamelServiceUsed (CamelServiceUsed value) {
            this.camelServiceUsed = value;
        }
        
  
        
        public ValueAddedServiceUsedList getValueAddedServiceUsedList () {
            return this.valueAddedServiceUsedList;
        }

        
        public boolean isValueAddedServiceUsedListPresent () {
            return this.valueAddedServiceUsedList != null;
        }
        

        public void setValueAddedServiceUsedList (ValueAddedServiceUsedList value) {
            this.valueAddedServiceUsedList = value;
        }
        
  
        
        public OperatorSpecInfoList getOperatorSpecInformation () {
            return this.operatorSpecInformation;
        }

        
        public boolean isOperatorSpecInformationPresent () {
            return this.operatorSpecInformation != null;
        }
        

        public void setOperatorSpecInformation (OperatorSpecInfoList value) {
            this.operatorSpecInformation = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_GprsCallSequenceType;
        }

       private static IASN1PreparedElementData preparedData_GprsCallSequenceType = CoderFactory.getInstance().newPreparedElementData(GprsCallSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "GprsCall", isOptional =  false , hasTag =  true, tag = 14, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private GprsCallSequenceType  value;        

        
        
        public GprsCall () {
        }
        
        
        
        public void setValue(GprsCallSequenceType value) {
            this.value = value;
        }
        
        
        
        public GprsCallSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GprsCall.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            