
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "GprsChargeableSubscriber" )
    public class GprsChargeableSubscriber implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "GprsChargeableSubscriber" , isSet = false )
       public static class GprsChargeableSubscriberSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "chargeableSubscriber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargeableSubscriber chargeableSubscriber = null;
                
  
        @ASN1Element ( name = "pdpType", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private PdpType pdpType = null;
                
  
        @ASN1Element ( name = "pdpAddress", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private PdpAddress pdpAddress = null;
                
  
        @ASN1Element ( name = "chargingCharacteristics", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargingCharacteristics chargingCharacteristics = null;
                
  
        
        public ChargeableSubscriber getChargeableSubscriber () {
            return this.chargeableSubscriber;
        }

        
        public boolean isChargeableSubscriberPresent () {
            return this.chargeableSubscriber != null;
        }
        

        public void setChargeableSubscriber (ChargeableSubscriber value) {
            this.chargeableSubscriber = value;
        }
        
  
        
        public PdpType getPdpType () {
            return this.pdpType;
        }

        
        public boolean isPdpTypePresent () {
            return this.pdpType != null;
        }
        

        public void setPdpType (PdpType value) {
            this.pdpType = value;
        }
        
  
        
        public PdpAddress getPdpAddress () {
            return this.pdpAddress;
        }

        
        public boolean isPdpAddressPresent () {
            return this.pdpAddress != null;
        }
        

        public void setPdpAddress (PdpAddress value) {
            this.pdpAddress = value;
        }
        
  
        
        public ChargingCharacteristics getChargingCharacteristics () {
            return this.chargingCharacteristics;
        }

        
        public boolean isChargingCharacteristicsPresent () {
            return this.chargingCharacteristics != null;
        }
        

        public void setChargingCharacteristics (ChargingCharacteristics value) {
            this.chargingCharacteristics = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_GprsChargeableSubscriberSequenceType;
        }

       private static IASN1PreparedElementData preparedData_GprsChargeableSubscriberSequenceType = CoderFactory.getInstance().newPreparedElementData(GprsChargeableSubscriberSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "GprsChargeableSubscriber", isOptional =  false , hasTag =  true, tag = 115, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private GprsChargeableSubscriberSequenceType  value;        

        
        
        public GprsChargeableSubscriber () {
        }
        
        
        
        public void setValue(GprsChargeableSubscriberSequenceType value) {
            this.value = value;
        }
        
        
        
        public GprsChargeableSubscriberSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GprsChargeableSubscriber.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            