
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "HSCSDParameterModification" )
    public class HSCSDParameterModification implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "HSCSDParameterModification" , isSet = false )
       public static class HSCSDParameterModificationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "aiur", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private AiurRequested aiur = null;
                
  
        @ASN1Element ( name = "maxNumberOfChannels", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NumberOfChannels maxNumberOfChannels = null;
                
  
        @ASN1Element ( name = "channelCodingUsed", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChannelCoding channelCodingUsed = null;
                
  
        @ASN1Element ( name = "numberOfChannelsUsed", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NumberOfChannelsUsed numberOfChannelsUsed = null;
                
  
        @ASN1Element ( name = "initiatingParty", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private InitiatingParty initiatingParty = null;
                
  
        @ASN1Element ( name = "modificationTimestamp", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ModificationTimestamp modificationTimestamp = null;
                
  
        
        public AiurRequested getAiur () {
            return this.aiur;
        }

        
        public boolean isAiurPresent () {
            return this.aiur != null;
        }
        

        public void setAiur (AiurRequested value) {
            this.aiur = value;
        }
        
  
        
        public NumberOfChannels getMaxNumberOfChannels () {
            return this.maxNumberOfChannels;
        }

        
        public boolean isMaxNumberOfChannelsPresent () {
            return this.maxNumberOfChannels != null;
        }
        

        public void setMaxNumberOfChannels (NumberOfChannels value) {
            this.maxNumberOfChannels = value;
        }
        
  
        
        public ChannelCoding getChannelCodingUsed () {
            return this.channelCodingUsed;
        }

        
        public boolean isChannelCodingUsedPresent () {
            return this.channelCodingUsed != null;
        }
        

        public void setChannelCodingUsed (ChannelCoding value) {
            this.channelCodingUsed = value;
        }
        
  
        
        public NumberOfChannelsUsed getNumberOfChannelsUsed () {
            return this.numberOfChannelsUsed;
        }

        
        public boolean isNumberOfChannelsUsedPresent () {
            return this.numberOfChannelsUsed != null;
        }
        

        public void setNumberOfChannelsUsed (NumberOfChannelsUsed value) {
            this.numberOfChannelsUsed = value;
        }
        
  
        
        public InitiatingParty getInitiatingParty () {
            return this.initiatingParty;
        }

        
        public boolean isInitiatingPartyPresent () {
            return this.initiatingParty != null;
        }
        

        public void setInitiatingParty (InitiatingParty value) {
            this.initiatingParty = value;
        }
        
  
        
        public ModificationTimestamp getModificationTimestamp () {
            return this.modificationTimestamp;
        }

        
        public boolean isModificationTimestampPresent () {
            return this.modificationTimestamp != null;
        }
        

        public void setModificationTimestamp (ModificationTimestamp value) {
            this.modificationTimestamp = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_HSCSDParameterModificationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_HSCSDParameterModificationSequenceType = CoderFactory.getInstance().newPreparedElementData(HSCSDParameterModificationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "HSCSDParameterModification", isOptional =  false , hasTag =  true, tag = 125, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private HSCSDParameterModificationSequenceType  value;        

        
        
        public HSCSDParameterModification () {
        }
        
        
        
        public void setValue(HSCSDParameterModificationSequenceType value) {
            this.value = value;
        }
        
        
        
        public HSCSDParameterModificationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(HSCSDParameterModification.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            