
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "LCSQosRequested" )
    public class LCSQosRequested implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "LCSQosRequested" , isSet = false )
       public static class LCSQosRequestedSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "lCSRequestTimestamp", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private LCSRequestTimestamp lCSRequestTimestamp = null;
                
  
        @ASN1Element ( name = "horizontalAccuracyRequested", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private HorizontalAccuracyRequested horizontalAccuracyRequested = null;
                
  
        @ASN1Element ( name = "verticalAccuracyRequested", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private VerticalAccuracyRequested verticalAccuracyRequested = null;
                
  
        @ASN1Element ( name = "responseTimeCategory", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ResponseTimeCategory responseTimeCategory = null;
                
  
        @ASN1Element ( name = "trackingPeriod", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TrackingPeriod trackingPeriod = null;
                
  
        @ASN1Element ( name = "trackingFrequency", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TrackingFrequency trackingFrequency = null;
                
  
        
        public LCSRequestTimestamp getLCSRequestTimestamp () {
            return this.lCSRequestTimestamp;
        }

        
        public boolean isLCSRequestTimestampPresent () {
            return this.lCSRequestTimestamp != null;
        }
        

        public void setLCSRequestTimestamp (LCSRequestTimestamp value) {
            this.lCSRequestTimestamp = value;
        }
        
  
        
        public HorizontalAccuracyRequested getHorizontalAccuracyRequested () {
            return this.horizontalAccuracyRequested;
        }

        
        public boolean isHorizontalAccuracyRequestedPresent () {
            return this.horizontalAccuracyRequested != null;
        }
        

        public void setHorizontalAccuracyRequested (HorizontalAccuracyRequested value) {
            this.horizontalAccuracyRequested = value;
        }
        
  
        
        public VerticalAccuracyRequested getVerticalAccuracyRequested () {
            return this.verticalAccuracyRequested;
        }

        
        public boolean isVerticalAccuracyRequestedPresent () {
            return this.verticalAccuracyRequested != null;
        }
        

        public void setVerticalAccuracyRequested (VerticalAccuracyRequested value) {
            this.verticalAccuracyRequested = value;
        }
        
  
        
        public ResponseTimeCategory getResponseTimeCategory () {
            return this.responseTimeCategory;
        }

        
        public boolean isResponseTimeCategoryPresent () {
            return this.responseTimeCategory != null;
        }
        

        public void setResponseTimeCategory (ResponseTimeCategory value) {
            this.responseTimeCategory = value;
        }
        
  
        
        public TrackingPeriod getTrackingPeriod () {
            return this.trackingPeriod;
        }

        
        public boolean isTrackingPeriodPresent () {
            return this.trackingPeriod != null;
        }
        

        public void setTrackingPeriod (TrackingPeriod value) {
            this.trackingPeriod = value;
        }
        
  
        
        public TrackingFrequency getTrackingFrequency () {
            return this.trackingFrequency;
        }

        
        public boolean isTrackingFrequencyPresent () {
            return this.trackingFrequency != null;
        }
        

        public void setTrackingFrequency (TrackingFrequency value) {
            this.trackingFrequency = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_LCSQosRequestedSequenceType;
        }

       private static IASN1PreparedElementData preparedData_LCSQosRequestedSequenceType = CoderFactory.getInstance().newPreparedElementData(LCSQosRequestedSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "LCSQosRequested", isOptional =  false , hasTag =  true, tag = 383, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private LCSQosRequestedSequenceType  value;        

        
        
        public LCSQosRequested () {
        }
        
        
        
        public void setValue(LCSQosRequestedSequenceType value) {
            this.value = value;
        }
        
        
        
        public LCSQosRequestedSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(LCSQosRequested.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            