
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "QoSRequested" )
    public class QoSRequested implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gsmQoSRequested", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GSMQoSRequested gsmQoSRequested = null;
                
  
        @ASN1Element ( name = "umtsQoSRequested", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UMTSQoSRequested umtsQoSRequested = null;
                
  
        
        public GSMQoSRequested getGsmQoSRequested () {
            return this.gsmQoSRequested;
        }

        public boolean isGsmQoSRequestedSelected () {
            return this.gsmQoSRequested != null;
        }

        private void setGsmQoSRequested (GSMQoSRequested value) {
            this.gsmQoSRequested = value;
        }

        
        public void selectGsmQoSRequested (GSMQoSRequested value) {
            this.gsmQoSRequested = value;
            
                    setUmtsQoSRequested(null);
                            
        }

        
  
        
        public UMTSQoSRequested getUmtsQoSRequested () {
            return this.umtsQoSRequested;
        }

        public boolean isUmtsQoSRequestedSelected () {
            return this.umtsQoSRequested != null;
        }

        private void setUmtsQoSRequested (UMTSQoSRequested value) {
            this.umtsQoSRequested = value;
        }

        
        public void selectUmtsQoSRequested (UMTSQoSRequested value) {
            this.umtsQoSRequested = value;
            
                    setGsmQoSRequested(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(QoSRequested.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            