
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "QoSUsed" )
    public class QoSUsed implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gsmQoSUsed", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GSMQoSUsed gsmQoSUsed = null;
                
  
        @ASN1Element ( name = "umtsQoSUsed", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UMTSQoSUsed umtsQoSUsed = null;
                
  
        
        public GSMQoSUsed getGsmQoSUsed () {
            return this.gsmQoSUsed;
        }

        public boolean isGsmQoSUsedSelected () {
            return this.gsmQoSUsed != null;
        }

        private void setGsmQoSUsed (GSMQoSUsed value) {
            this.gsmQoSUsed = value;
        }

        
        public void selectGsmQoSUsed (GSMQoSUsed value) {
            this.gsmQoSUsed = value;
            
                    setUmtsQoSUsed(null);
                            
        }

        
  
        
        public UMTSQoSUsed getUmtsQoSUsed () {
            return this.umtsQoSUsed;
        }

        public boolean isUmtsQoSUsedSelected () {
            return this.umtsQoSUsed != null;
        }

        private void setUmtsQoSUsed (UMTSQoSUsed value) {
            this.umtsQoSUsed = value;
        }

        
        public void selectUmtsQoSUsed (UMTSQoSUsed value) {
            this.umtsQoSUsed = value;
            
                    setGsmQoSUsed(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(QoSUsed.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            