
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "RapFileSequenceNumber" )
    public class RapFileSequenceNumber implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "RapFileSequenceNumber", isOptional =  false , hasTag =  true, tag = 181, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private FileSequenceNumber  value;        

        
        
        public RapFileSequenceNumber () {
        }
        
        
        
        public void setValue(FileSequenceNumber value) {
            this.value = value;
        }
        
        
        
        public FileSequenceNumber getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RapFileSequenceNumber.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            