
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "RecEntityId" )
    public class RecEntityId implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gmlcAddress", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GmlcAddress gmlcAddress = null;
                
  
        @ASN1Element ( name = "mscId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MscId mscId = null;
                
  
        @ASN1Element ( name = "msisdn", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Msisdn msisdn = null;
                
  
        @ASN1Element ( name = "gsnaddress", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GsnAddress gsnaddress = null;
                
  
        
        public GmlcAddress getGmlcAddress () {
            return this.gmlcAddress;
        }

        public boolean isGmlcAddressSelected () {
            return this.gmlcAddress != null;
        }

        private void setGmlcAddress (GmlcAddress value) {
            this.gmlcAddress = value;
        }

        
        public void selectGmlcAddress (GmlcAddress value) {
            this.gmlcAddress = value;
            
                    setMscId(null);
                
                    setMsisdn(null);
                
                    setGsnaddress(null);
                            
        }

        
  
        
        public MscId getMscId () {
            return this.mscId;
        }

        public boolean isMscIdSelected () {
            return this.mscId != null;
        }

        private void setMscId (MscId value) {
            this.mscId = value;
        }

        
        public void selectMscId (MscId value) {
            this.mscId = value;
            
                    setGmlcAddress(null);
                
                    setMsisdn(null);
                
                    setGsnaddress(null);
                            
        }

        
  
        
        public Msisdn getMsisdn () {
            return this.msisdn;
        }

        public boolean isMsisdnSelected () {
            return this.msisdn != null;
        }

        private void setMsisdn (Msisdn value) {
            this.msisdn = value;
        }

        
        public void selectMsisdn (Msisdn value) {
            this.msisdn = value;
            
                    setGmlcAddress(null);
                
                    setMscId(null);
                
                    setGsnaddress(null);
                            
        }

        
  
        
        public GsnAddress getGsnaddress () {
            return this.gsnaddress;
        }

        public boolean isGsnaddressSelected () {
            return this.gsnaddress != null;
        }

        private void setGsnaddress (GsnAddress value) {
            this.gsnaddress = value;
        }

        
        public void selectGsnaddress (GsnAddress value) {
            this.gsnaddress = value;
            
                    setGmlcAddress(null);
                
                    setMscId(null);
                
                    setMsisdn(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RecEntityId.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            