
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Taxation" )
    public class Taxation implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "Taxation" , isSet = false )
       public static class TaxationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "taxCode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TaxCode taxCode = null;
                
  
        @ASN1Element ( name = "taxType", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TaxType taxType = null;
                
  
        @ASN1Element ( name = "taxRate", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TaxRate taxRate = null;
                
  
        
        public TaxCode getTaxCode () {
            return this.taxCode;
        }

        
        public boolean isTaxCodePresent () {
            return this.taxCode != null;
        }
        

        public void setTaxCode (TaxCode value) {
            this.taxCode = value;
        }
        
  
        
        public TaxType getTaxType () {
            return this.taxType;
        }

        
        public boolean isTaxTypePresent () {
            return this.taxType != null;
        }
        

        public void setTaxType (TaxType value) {
            this.taxType = value;
        }
        
  
        
        public TaxRate getTaxRate () {
            return this.taxRate;
        }

        
        public boolean isTaxRatePresent () {
            return this.taxRate != null;
        }
        

        public void setTaxRate (TaxRate value) {
            this.taxRate = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_TaxationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_TaxationSequenceType = CoderFactory.getInstance().newPreparedElementData(TaxationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "Taxation", isOptional =  false , hasTag =  true, tag = 216, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private TaxationSequenceType  value;        

        
        
        public Taxation () {
        }
        
        
        
        public void setValue(TaxationSequenceType value) {
            this.value = value;
        }
        
        
        
        public TaxationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Taxation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            