
package el.data.asn310;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ValueAddedServiceUsed" )
    public class ValueAddedServiceUsed implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ValueAddedServiceUsed" , isSet = false )
       public static class ValueAddedServiceUsedSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "vasCode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private VasCode vasCode = null;
                
  
        @ASN1Element ( name = "chargingTimeStamp", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargingTimeStamp chargingTimeStamp = null;
                
  
        @ASN1Element ( name = "chargeInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargeInformation chargeInformation = null;
                
  
        
        public VasCode getVasCode () {
            return this.vasCode;
        }

        
        public boolean isVasCodePresent () {
            return this.vasCode != null;
        }
        

        public void setVasCode (VasCode value) {
            this.vasCode = value;
        }
        
  
        
        public ChargingTimeStamp getChargingTimeStamp () {
            return this.chargingTimeStamp;
        }

        
        public boolean isChargingTimeStampPresent () {
            return this.chargingTimeStamp != null;
        }
        

        public void setChargingTimeStamp (ChargingTimeStamp value) {
            this.chargingTimeStamp = value;
        }
        
  
        
        public ChargeInformation getChargeInformation () {
            return this.chargeInformation;
        }

        
        public boolean isChargeInformationPresent () {
            return this.chargeInformation != null;
        }
        

        public void setChargeInformation (ChargeInformation value) {
            this.chargeInformation = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ValueAddedServiceUsedSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ValueAddedServiceUsedSequenceType = CoderFactory.getInstance().newPreparedElementData(ValueAddedServiceUsedSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ValueAddedServiceUsed", isOptional =  false , hasTag =  true, tag = 236, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ValueAddedServiceUsedSequenceType  value;        

        
        
        public ValueAddedServiceUsed () {
        }
        
        
        
        public void setValue(ValueAddedServiceUsedSequenceType value) {
            this.value = value;
        }
        
        
        
        public ValueAddedServiceUsedSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ValueAddedServiceUsed.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            