
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "CallingNumber" )
    public class CallingNumber implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "CallingNumber", isOptional =  false , hasTag =  true, tag = 405, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private AddressStringDigits  value;        

        
        
        public CallingNumber () {
        }
        
        
        
        public void setValue(AddressStringDigits value) {
            this.value = value;
        }
        
        
        
        public AddressStringDigits getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CallingNumber.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            