
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "CamelServiceUsed" )
    public class CamelServiceUsed implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "CamelServiceUsed" , isSet = false )
       public static class CamelServiceUsedSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "camelServiceLevel", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CamelServiceLevel camelServiceLevel = null;
                
  
        @ASN1Element ( name = "camelServiceKey", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CamelServiceKey camelServiceKey = null;
                
  
        @ASN1Element ( name = "defaultCallHandling", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DefaultCallHandlingIndicator defaultCallHandling = null;
                
  
        @ASN1Element ( name = "exchangeRateCode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ExchangeRateCode exchangeRateCode = null;
                
  
        @ASN1Element ( name = "taxInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TaxInformationList taxInformation = null;
                
  
        @ASN1Element ( name = "discountInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DiscountInformation discountInformation = null;
                
  
        @ASN1Element ( name = "camelInvocationFee", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CamelInvocationFee camelInvocationFee = null;
                
  
        @ASN1Element ( name = "threeGcamelDestination", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ThreeGcamelDestination threeGcamelDestination = null;
                
  
        @ASN1Element ( name = "cseInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CseInformation cseInformation = null;
                
  
        
        public CamelServiceLevel getCamelServiceLevel () {
            return this.camelServiceLevel;
        }

        
        public boolean isCamelServiceLevelPresent () {
            return this.camelServiceLevel != null;
        }
        

        public void setCamelServiceLevel (CamelServiceLevel value) {
            this.camelServiceLevel = value;
        }
        
  
        
        public CamelServiceKey getCamelServiceKey () {
            return this.camelServiceKey;
        }

        
        public boolean isCamelServiceKeyPresent () {
            return this.camelServiceKey != null;
        }
        

        public void setCamelServiceKey (CamelServiceKey value) {
            this.camelServiceKey = value;
        }
        
  
        
        public DefaultCallHandlingIndicator getDefaultCallHandling () {
            return this.defaultCallHandling;
        }

        
        public boolean isDefaultCallHandlingPresent () {
            return this.defaultCallHandling != null;
        }
        

        public void setDefaultCallHandling (DefaultCallHandlingIndicator value) {
            this.defaultCallHandling = value;
        }
        
  
        
        public ExchangeRateCode getExchangeRateCode () {
            return this.exchangeRateCode;
        }

        
        public boolean isExchangeRateCodePresent () {
            return this.exchangeRateCode != null;
        }
        

        public void setExchangeRateCode (ExchangeRateCode value) {
            this.exchangeRateCode = value;
        }
        
  
        
        public TaxInformationList getTaxInformation () {
            return this.taxInformation;
        }

        
        public boolean isTaxInformationPresent () {
            return this.taxInformation != null;
        }
        

        public void setTaxInformation (TaxInformationList value) {
            this.taxInformation = value;
        }
        
  
        
        public DiscountInformation getDiscountInformation () {
            return this.discountInformation;
        }

        
        public boolean isDiscountInformationPresent () {
            return this.discountInformation != null;
        }
        

        public void setDiscountInformation (DiscountInformation value) {
            this.discountInformation = value;
        }
        
  
        
        public CamelInvocationFee getCamelInvocationFee () {
            return this.camelInvocationFee;
        }

        
        public boolean isCamelInvocationFeePresent () {
            return this.camelInvocationFee != null;
        }
        

        public void setCamelInvocationFee (CamelInvocationFee value) {
            this.camelInvocationFee = value;
        }
        
  
        
        public ThreeGcamelDestination getThreeGcamelDestination () {
            return this.threeGcamelDestination;
        }

        
        public boolean isThreeGcamelDestinationPresent () {
            return this.threeGcamelDestination != null;
        }
        

        public void setThreeGcamelDestination (ThreeGcamelDestination value) {
            this.threeGcamelDestination = value;
        }
        
  
        
        public CseInformation getCseInformation () {
            return this.cseInformation;
        }

        
        public boolean isCseInformationPresent () {
            return this.cseInformation != null;
        }
        

        public void setCseInformation (CseInformation value) {
            this.cseInformation = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_CamelServiceUsedSequenceType;
        }

       private static IASN1PreparedElementData preparedData_CamelServiceUsedSequenceType = CoderFactory.getInstance().newPreparedElementData(CamelServiceUsedSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "CamelServiceUsed", isOptional =  false , hasTag =  true, tag = 57, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private CamelServiceUsedSequenceType  value;        

        
        
        public CamelServiceUsed () {
        }
        
        
        
        public void setValue(CamelServiceUsedSequenceType value) {
            this.value = value;
        }
        
        
        
        public CamelServiceUsedSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CamelServiceUsed.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            