
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ChargeInformation" )
    public class ChargeInformation implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ChargeInformation" , isSet = false )
       public static class ChargeInformationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "chargedItem", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargedItem chargedItem = null;
                
  
        @ASN1Element ( name = "exchangeRateCode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ExchangeRateCode exchangeRateCode = null;
                
  
        @ASN1Element ( name = "callTypeGroup", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CallTypeGroup callTypeGroup = null;
                
  
        @ASN1Element ( name = "chargeDetailList", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargeDetailList chargeDetailList = null;
                
  
        @ASN1Element ( name = "taxInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TaxInformationList taxInformation = null;
                
  
        @ASN1Element ( name = "discountInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DiscountInformation discountInformation = null;
                
  
        
        public ChargedItem getChargedItem () {
            return this.chargedItem;
        }

        
        public boolean isChargedItemPresent () {
            return this.chargedItem != null;
        }
        

        public void setChargedItem (ChargedItem value) {
            this.chargedItem = value;
        }
        
  
        
        public ExchangeRateCode getExchangeRateCode () {
            return this.exchangeRateCode;
        }

        
        public boolean isExchangeRateCodePresent () {
            return this.exchangeRateCode != null;
        }
        

        public void setExchangeRateCode (ExchangeRateCode value) {
            this.exchangeRateCode = value;
        }
        
  
        
        public CallTypeGroup getCallTypeGroup () {
            return this.callTypeGroup;
        }

        
        public boolean isCallTypeGroupPresent () {
            return this.callTypeGroup != null;
        }
        

        public void setCallTypeGroup (CallTypeGroup value) {
            this.callTypeGroup = value;
        }
        
  
        
        public ChargeDetailList getChargeDetailList () {
            return this.chargeDetailList;
        }

        
        public boolean isChargeDetailListPresent () {
            return this.chargeDetailList != null;
        }
        

        public void setChargeDetailList (ChargeDetailList value) {
            this.chargeDetailList = value;
        }
        
  
        
        public TaxInformationList getTaxInformation () {
            return this.taxInformation;
        }

        
        public boolean isTaxInformationPresent () {
            return this.taxInformation != null;
        }
        

        public void setTaxInformation (TaxInformationList value) {
            this.taxInformation = value;
        }
        
  
        
        public DiscountInformation getDiscountInformation () {
            return this.discountInformation;
        }

        
        public boolean isDiscountInformationPresent () {
            return this.discountInformation != null;
        }
        

        public void setDiscountInformation (DiscountInformation value) {
            this.discountInformation = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ChargeInformationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ChargeInformationSequenceType = CoderFactory.getInstance().newPreparedElementData(ChargeInformationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ChargeInformation", isOptional =  false , hasTag =  true, tag = 69, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ChargeInformationSequenceType  value;        

        
        
        public ChargeInformation () {
        }
        
        
        
        public void setValue(ChargeInformationSequenceType value) {
            this.value = value;
        }
        
        
        
        public ChargeInformationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ChargeInformation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            