
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ChargedParty" )
    public class ChargedParty implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ChargedParty" , isSet = false )
       public static class ChargedPartySequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "imsi", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Imsi imsi = null;
                
  
        @ASN1Element ( name = "msisdn", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Msisdn msisdn = null;
                
  
        @ASN1Element ( name = "publicUserId", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private PublicUserId publicUserId = null;
                
  
        @ASN1Element ( name = "homeBid", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private HomeBid homeBid = null;
                
  
        @ASN1Element ( name = "homeLocationDescription", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private HomeLocationDescription homeLocationDescription = null;
                
  
        @ASN1Element ( name = "imei", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Imei imei = null;
                
  
        
        public Imsi getImsi () {
            return this.imsi;
        }

        
        public boolean isImsiPresent () {
            return this.imsi != null;
        }
        

        public void setImsi (Imsi value) {
            this.imsi = value;
        }
        
  
        
        public Msisdn getMsisdn () {
            return this.msisdn;
        }

        
        public boolean isMsisdnPresent () {
            return this.msisdn != null;
        }
        

        public void setMsisdn (Msisdn value) {
            this.msisdn = value;
        }
        
  
        
        public PublicUserId getPublicUserId () {
            return this.publicUserId;
        }

        
        public boolean isPublicUserIdPresent () {
            return this.publicUserId != null;
        }
        

        public void setPublicUserId (PublicUserId value) {
            this.publicUserId = value;
        }
        
  
        
        public HomeBid getHomeBid () {
            return this.homeBid;
        }

        
        public boolean isHomeBidPresent () {
            return this.homeBid != null;
        }
        

        public void setHomeBid (HomeBid value) {
            this.homeBid = value;
        }
        
  
        
        public HomeLocationDescription getHomeLocationDescription () {
            return this.homeLocationDescription;
        }

        
        public boolean isHomeLocationDescriptionPresent () {
            return this.homeLocationDescription != null;
        }
        

        public void setHomeLocationDescription (HomeLocationDescription value) {
            this.homeLocationDescription = value;
        }
        
  
        
        public Imei getImei () {
            return this.imei;
        }

        
        public boolean isImeiPresent () {
            return this.imei != null;
        }
        

        public void setImei (Imei value) {
            this.imei = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ChargedPartySequenceType;
        }

       private static IASN1PreparedElementData preparedData_ChargedPartySequenceType = CoderFactory.getInstance().newPreparedElementData(ChargedPartySequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ChargedParty", isOptional =  false , hasTag =  true, tag = 436, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ChargedPartySequenceType  value;        

        
        
        public ChargedParty () {
        }
        
        
        
        public void setValue(ChargedPartySequenceType value) {
            this.value = value;
        }
        
        
        
        public ChargedPartySequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ChargedParty.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            