
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ChargedPartyHomeIdentification" )
    public class ChargedPartyHomeIdentification implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ChargedPartyHomeIdentification" , isSet = false )
       public static class ChargedPartyHomeIdentificationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "homeIdType", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private HomeIdType homeIdType = null;
                
  
        @ASN1Element ( name = "homeIdentifier", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private HomeIdentifier homeIdentifier = null;
                
  
        
        public HomeIdType getHomeIdType () {
            return this.homeIdType;
        }

        
        public boolean isHomeIdTypePresent () {
            return this.homeIdType != null;
        }
        

        public void setHomeIdType (HomeIdType value) {
            this.homeIdType = value;
        }
        
  
        
        public HomeIdentifier getHomeIdentifier () {
            return this.homeIdentifier;
        }

        
        public boolean isHomeIdentifierPresent () {
            return this.homeIdentifier != null;
        }
        

        public void setHomeIdentifier (HomeIdentifier value) {
            this.homeIdentifier = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ChargedPartyHomeIdentificationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ChargedPartyHomeIdentificationSequenceType = CoderFactory.getInstance().newPreparedElementData(ChargedPartyHomeIdentificationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ChargedPartyHomeIdentification", isOptional =  false , hasTag =  true, tag = 313, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ChargedPartyHomeIdentificationSequenceType  value;        

        
        
        public ChargedPartyHomeIdentification () {
        }
        
        
        
        public void setValue(ChargedPartyHomeIdentificationSequenceType value) {
            this.value = value;
        }
        
        
        
        public ChargedPartyHomeIdentificationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ChargedPartyHomeIdentification.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            