
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "HomeLocationDescription" )
    public class HomeLocationDescription implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "HomeLocationDescription", isOptional =  false , hasTag =  true, tag = 413, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private LocationDescription  value;        

        
        
        public HomeLocationDescription () {
        }
        
        
        
        public void setValue(LocationDescription value) {
            this.value = value;
        }
        
        
        
        public LocationDescription getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(HomeLocationDescription.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            