
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "NonChargedParty" )
    public class NonChargedParty implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "NonChargedParty" , isSet = false )
       public static class NonChargedPartySequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "nonChargedPartyNumber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonChargedPartyNumber nonChargedPartyNumber = null;
                
  
        @ASN1Element ( name = "nonChargedPublicUserId", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonChargedPublicUserId nonChargedPublicUserId = null;
                
  
        
        public NonChargedPartyNumber getNonChargedPartyNumber () {
            return this.nonChargedPartyNumber;
        }

        
        public boolean isNonChargedPartyNumberPresent () {
            return this.nonChargedPartyNumber != null;
        }
        

        public void setNonChargedPartyNumber (NonChargedPartyNumber value) {
            this.nonChargedPartyNumber = value;
        }
        
  
        
        public NonChargedPublicUserId getNonChargedPublicUserId () {
            return this.nonChargedPublicUserId;
        }

        
        public boolean isNonChargedPublicUserIdPresent () {
            return this.nonChargedPublicUserId != null;
        }
        

        public void setNonChargedPublicUserId (NonChargedPublicUserId value) {
            this.nonChargedPublicUserId = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_NonChargedPartySequenceType;
        }

       private static IASN1PreparedElementData preparedData_NonChargedPartySequenceType = CoderFactory.getInstance().newPreparedElementData(NonChargedPartySequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "NonChargedParty", isOptional =  false , hasTag =  true, tag = 443, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private NonChargedPartySequenceType  value;        

        
        
        public NonChargedParty () {
        }
        
        
        
        public void setValue(NonChargedPartySequenceType value) {
            this.value = value;
        }
        
        
        
        public NonChargedPartySequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(NonChargedParty.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            