
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TotalAdvisedChargeValue" )
    public class TotalAdvisedChargeValue implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "TotalAdvisedChargeValue" , isSet = false )
       public static class TotalAdvisedChargeValueSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "advisedChargeCurrency", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private AdvisedChargeCurrency advisedChargeCurrency = null;
                
  
        @ASN1Element ( name = "totalAdvisedCharge", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TotalAdvisedCharge totalAdvisedCharge = null;
                
  
        @ASN1Element ( name = "totalAdvisedChargeRefund", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TotalAdvisedChargeRefund totalAdvisedChargeRefund = null;
                
  
        @ASN1Element ( name = "totalCommission", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TotalCommission totalCommission = null;
                
  
        @ASN1Element ( name = "totalCommissionRefund", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TotalCommissionRefund totalCommissionRefund = null;
                
  
        
        public AdvisedChargeCurrency getAdvisedChargeCurrency () {
            return this.advisedChargeCurrency;
        }

        
        public boolean isAdvisedChargeCurrencyPresent () {
            return this.advisedChargeCurrency != null;
        }
        

        public void setAdvisedChargeCurrency (AdvisedChargeCurrency value) {
            this.advisedChargeCurrency = value;
        }
        
  
        
        public TotalAdvisedCharge getTotalAdvisedCharge () {
            return this.totalAdvisedCharge;
        }

        
        public boolean isTotalAdvisedChargePresent () {
            return this.totalAdvisedCharge != null;
        }
        

        public void setTotalAdvisedCharge (TotalAdvisedCharge value) {
            this.totalAdvisedCharge = value;
        }
        
  
        
        public TotalAdvisedChargeRefund getTotalAdvisedChargeRefund () {
            return this.totalAdvisedChargeRefund;
        }

        
        public boolean isTotalAdvisedChargeRefundPresent () {
            return this.totalAdvisedChargeRefund != null;
        }
        

        public void setTotalAdvisedChargeRefund (TotalAdvisedChargeRefund value) {
            this.totalAdvisedChargeRefund = value;
        }
        
  
        
        public TotalCommission getTotalCommission () {
            return this.totalCommission;
        }

        
        public boolean isTotalCommissionPresent () {
            return this.totalCommission != null;
        }
        

        public void setTotalCommission (TotalCommission value) {
            this.totalCommission = value;
        }
        
  
        
        public TotalCommissionRefund getTotalCommissionRefund () {
            return this.totalCommissionRefund;
        }

        
        public boolean isTotalCommissionRefundPresent () {
            return this.totalCommissionRefund != null;
        }
        

        public void setTotalCommissionRefund (TotalCommissionRefund value) {
            this.totalCommissionRefund = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_TotalAdvisedChargeValueSequenceType;
        }

       private static IASN1PreparedElementData preparedData_TotalAdvisedChargeValueSequenceType = CoderFactory.getInstance().newPreparedElementData(TotalAdvisedChargeValueSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "TotalAdvisedChargeValue", isOptional =  false , hasTag =  true, tag = 360, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private TotalAdvisedChargeValueSequenceType  value;        

        
        
        public TotalAdvisedChargeValue () {
        }
        
        
        
        public void setValue(TotalAdvisedChargeValueSequenceType value) {
            this.value = value;
        }
        
        
        
        public TotalAdvisedChargeValueSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TotalAdvisedChargeValue.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            