
package el.data.asn312;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "UtcTimeOffsetInfo" )
    public class UtcTimeOffsetInfo implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "UtcTimeOffsetInfo" , isSet = false )
       public static class UtcTimeOffsetInfoSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "utcTimeOffsetCode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private UtcTimeOffsetCode utcTimeOffsetCode = null;
                
  
        @ASN1Element ( name = "utcTimeOffset", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private UtcTimeOffset utcTimeOffset = null;
                
  
        
        public UtcTimeOffsetCode getUtcTimeOffsetCode () {
            return this.utcTimeOffsetCode;
        }

        
        public boolean isUtcTimeOffsetCodePresent () {
            return this.utcTimeOffsetCode != null;
        }
        

        public void setUtcTimeOffsetCode (UtcTimeOffsetCode value) {
            this.utcTimeOffsetCode = value;
        }
        
  
        
        public UtcTimeOffset getUtcTimeOffset () {
            return this.utcTimeOffset;
        }

        
        public boolean isUtcTimeOffsetPresent () {
            return this.utcTimeOffset != null;
        }
        

        public void setUtcTimeOffset (UtcTimeOffset value) {
            this.utcTimeOffset = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_UtcTimeOffsetInfoSequenceType;
        }

       private static IASN1PreparedElementData preparedData_UtcTimeOffsetInfoSequenceType = CoderFactory.getInstance().newPreparedElementData(UtcTimeOffsetInfoSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "UtcTimeOffsetInfo", isOptional =  false , hasTag =  true, tag = 233, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private UtcTimeOffsetInfoSequenceType  value;        

        
        
        public UtcTimeOffsetInfo () {
        }
        
        
        
        public void setValue(UtcTimeOffsetInfoSequenceType value) {
            this.value = value;
        }
        
        
        
        public UtcTimeOffsetInfoSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UtcTimeOffsetInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            