
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DateTime", isSet = false )
    public class DateTime implements IASN1PreparedElement {
            
        @ASN1Element ( name = "localTimeStamp", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private LocalTimeStamp localTimeStamp = null;
                
  
        @ASN1Element ( name = "utcTimeOffsetCode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private UtcTimeOffsetCode utcTimeOffsetCode = null;
                
  
        
        public LocalTimeStamp getLocalTimeStamp () {
            return this.localTimeStamp;
        }

        
        public boolean isLocalTimeStampPresent () {
            return this.localTimeStamp != null;
        }
        

        public void setLocalTimeStamp (LocalTimeStamp value) {
            this.localTimeStamp = value;
        }
        
  
        
        public UtcTimeOffsetCode getUtcTimeOffsetCode () {
            return this.utcTimeOffsetCode;
        }

        
        public boolean isUtcTimeOffsetCodePresent () {
            return this.utcTimeOffsetCode != null;
        }
        

        public void setUtcTimeOffsetCode (UtcTimeOffsetCode value) {
            this.utcTimeOffsetCode = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DateTime.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            