
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "DiscountInformation" )
    public class DiscountInformation implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "DiscountInformation" , isSet = false )
       public static class DiscountInformationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "discountCode", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DiscountCode discountCode = null;
                
  
        @ASN1Element ( name = "discount", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Discount discount = null;
                
  
        @ASN1Element ( name = "discountableAmount", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DiscountableAmount discountableAmount = null;
                
  
        
        public DiscountCode getDiscountCode () {
            return this.discountCode;
        }

        
        public boolean isDiscountCodePresent () {
            return this.discountCode != null;
        }
        

        public void setDiscountCode (DiscountCode value) {
            this.discountCode = value;
        }
        
  
        
        public Discount getDiscount () {
            return this.discount;
        }

        
        public boolean isDiscountPresent () {
            return this.discount != null;
        }
        

        public void setDiscount (Discount value) {
            this.discount = value;
        }
        
  
        
        public DiscountableAmount getDiscountableAmount () {
            return this.discountableAmount;
        }

        
        public boolean isDiscountableAmountPresent () {
            return this.discountableAmount != null;
        }
        

        public void setDiscountableAmount (DiscountableAmount value) {
            this.discountableAmount = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_DiscountInformationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_DiscountInformationSequenceType = CoderFactory.getInstance().newPreparedElementData(DiscountInformationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "DiscountInformation", isOptional =  false , hasTag =  true, tag = 96, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private DiscountInformationSequenceType  value;        

        
        
        public DiscountInformation () {
        }
        
        
        
        public void setValue(DiscountInformationSequenceType value) {
            this.value = value;
        }
        
        
        
        public DiscountInformationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DiscountInformation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            