
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "GprsNetworkLocation" )
    public class GprsNetworkLocation implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "GprsNetworkLocation" , isSet = false )
       public static class GprsNetworkLocationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "recEntity", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private RecEntityCodeList recEntity = null;
                
  
        @ASN1Element ( name = "locationArea", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private LocationArea locationArea = null;
                
  
        @ASN1Element ( name = "cellId", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CellId cellId = null;
                
  
        
        public RecEntityCodeList getRecEntity () {
            return this.recEntity;
        }

        
        public boolean isRecEntityPresent () {
            return this.recEntity != null;
        }
        

        public void setRecEntity (RecEntityCodeList value) {
            this.recEntity = value;
        }
        
  
        
        public LocationArea getLocationArea () {
            return this.locationArea;
        }

        
        public boolean isLocationAreaPresent () {
            return this.locationArea != null;
        }
        

        public void setLocationArea (LocationArea value) {
            this.locationArea = value;
        }
        
  
        
        public CellId getCellId () {
            return this.cellId;
        }

        
        public boolean isCellIdPresent () {
            return this.cellId != null;
        }
        

        public void setCellId (CellId value) {
            this.cellId = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_GprsNetworkLocationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_GprsNetworkLocationSequenceType = CoderFactory.getInstance().newPreparedElementData(GprsNetworkLocationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "GprsNetworkLocation", isOptional =  false , hasTag =  true, tag = 118, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private GprsNetworkLocationSequenceType  value;        

        
        
        public GprsNetworkLocation () {
        }
        
        
        
        public void setValue(GprsNetworkLocationSequenceType value) {
            this.value = value;
        }
        
        
        
        public GprsNetworkLocationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GprsNetworkLocation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            