
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "GprsLocationInformation" )
    public class GprsLocationInformation implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "GprsLocationInformation" , isSet = false )
       public static class GprsLocationInformationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gprsNetworkLocation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GprsNetworkLocation gprsNetworkLocation = null;
                
  
        @ASN1Element ( name = "homeLocationInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private HomeLocationInformation homeLocationInformation = null;
                
  
        @ASN1Element ( name = "geographicalLocation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GeographicalLocation geographicalLocation = null;
                
  
        
        public GprsNetworkLocation getGprsNetworkLocation () {
            return this.gprsNetworkLocation;
        }

        
        public boolean isGprsNetworkLocationPresent () {
            return this.gprsNetworkLocation != null;
        }
        

        public void setGprsNetworkLocation (GprsNetworkLocation value) {
            this.gprsNetworkLocation = value;
        }
        
  
        
        public HomeLocationInformation getHomeLocationInformation () {
            return this.homeLocationInformation;
        }

        
        public boolean isHomeLocationInformationPresent () {
            return this.homeLocationInformation != null;
        }
        

        public void setHomeLocationInformation (HomeLocationInformation value) {
            this.homeLocationInformation = value;
        }
        
  
        
        public GeographicalLocation getGeographicalLocation () {
            return this.geographicalLocation;
        }

        
        public boolean isGeographicalLocationPresent () {
            return this.geographicalLocation != null;
        }
        

        public void setGeographicalLocation (GeographicalLocation value) {
            this.geographicalLocation = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_GprsLocationInformationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_GprsLocationInformationSequenceType = CoderFactory.getInstance().newPreparedElementData(GprsLocationInformationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "GprsLocationInformation", isOptional =  false , hasTag =  true, tag = 117, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private GprsLocationInformationSequenceType  value;        

        
        
        public GprsLocationInformation () {
        }
        
        
        
        public void setValue(GprsLocationInformationSequenceType value) {
            this.value = value;
        }
        
        
        
        public GprsLocationInformationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GprsLocationInformation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            