
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ImeiOrEsn" )
    public class ImeiOrEsn implements IASN1PreparedElement {
                
        
        
    @ASN1PreparedElement
    @ASN1Choice ( name = "ImeiOrEsn" )
    public static class ImeiOrEsnChoiceType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "imei", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Imei imei = null;
                
  
        @ASN1Element ( name = "esn", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Esn esn = null;
                
  
        
        public Imei getImei () {
            return this.imei;
        }

        public boolean isImeiSelected () {
            return this.imei != null;
        }

        private void setImei (Imei value) {
            this.imei = value;
        }

        
        public void selectImei (Imei value) {
            this.imei = value;
            
                    setEsn(null);
                            
        }

        
  
        
        public Esn getEsn () {
            return this.esn;
        }

        public boolean isEsnSelected () {
            return this.esn != null;
        }

        private void setEsn (Esn value) {
            this.esn = value;
        }

        
        public void selectEsn (Esn value) {
            this.esn = value;
            
                    setImei(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ImeiOrEsnChoiceType;
        }

        private static IASN1PreparedElementData preparedData_ImeiOrEsnChoiceType = CoderFactory.getInstance().newPreparedElementData(ImeiOrEsnChoiceType.class);

    }

                
        @ASN1Element ( name = "ImeiOrEsn", isOptional =  false , hasTag =  true, tag = 429, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ImeiOrEsnChoiceType  value;        

        
        
        public ImeiOrEsn () {
        }
        
        
        
        public void setValue(ImeiOrEsnChoiceType value) {
            this.value = value;
        }
        
        
        
        public ImeiOrEsnChoiceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ImeiOrEsn.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            