
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ScuBasicInformation" )
    public class ScuBasicInformation implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ScuBasicInformation" , isSet = false )
       public static class ScuBasicInformationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "chargeableSubscriber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ScuChargeableSubscriber chargeableSubscriber = null;
                
  
        @ASN1Element ( name = "chargedPartyStatus", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargedPartyStatus chargedPartyStatus = null;
                
  
        @ASN1Element ( name = "nonChargedNumber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonChargedNumber nonChargedNumber = null;
                
  
        @ASN1Element ( name = "clirIndicator", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ClirIndicator clirIndicator = null;
                
  
        @ASN1Element ( name = "originatingNetwork", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private OriginatingNetwork originatingNetwork = null;
                
  
        @ASN1Element ( name = "destinationNetwork", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DestinationNetwork destinationNetwork = null;
                
  
        
        public ScuChargeableSubscriber getChargeableSubscriber () {
            return this.chargeableSubscriber;
        }

        
        public boolean isChargeableSubscriberPresent () {
            return this.chargeableSubscriber != null;
        }
        

        public void setChargeableSubscriber (ScuChargeableSubscriber value) {
            this.chargeableSubscriber = value;
        }
        
  
        
        public ChargedPartyStatus getChargedPartyStatus () {
            return this.chargedPartyStatus;
        }

        
        public boolean isChargedPartyStatusPresent () {
            return this.chargedPartyStatus != null;
        }
        

        public void setChargedPartyStatus (ChargedPartyStatus value) {
            this.chargedPartyStatus = value;
        }
        
  
        
        public NonChargedNumber getNonChargedNumber () {
            return this.nonChargedNumber;
        }

        
        public boolean isNonChargedNumberPresent () {
            return this.nonChargedNumber != null;
        }
        

        public void setNonChargedNumber (NonChargedNumber value) {
            this.nonChargedNumber = value;
        }
        
  
        
        public ClirIndicator getClirIndicator () {
            return this.clirIndicator;
        }

        
        public boolean isClirIndicatorPresent () {
            return this.clirIndicator != null;
        }
        

        public void setClirIndicator (ClirIndicator value) {
            this.clirIndicator = value;
        }
        
  
        
        public OriginatingNetwork getOriginatingNetwork () {
            return this.originatingNetwork;
        }

        
        public boolean isOriginatingNetworkPresent () {
            return this.originatingNetwork != null;
        }
        

        public void setOriginatingNetwork (OriginatingNetwork value) {
            this.originatingNetwork = value;
        }
        
  
        
        public DestinationNetwork getDestinationNetwork () {
            return this.destinationNetwork;
        }

        
        public boolean isDestinationNetworkPresent () {
            return this.destinationNetwork != null;
        }
        

        public void setDestinationNetwork (DestinationNetwork value) {
            this.destinationNetwork = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ScuBasicInformationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ScuBasicInformationSequenceType = CoderFactory.getInstance().newPreparedElementData(ScuBasicInformationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ScuBasicInformation", isOptional =  false , hasTag =  true, tag = 191, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ScuBasicInformationSequenceType  value;        

        
        
        public ScuBasicInformation () {
        }
        
        
        
        public void setValue(ScuBasicInformationSequenceType value) {
            this.value = value;
        }
        
        
        
        public ScuBasicInformationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ScuBasicInformation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            