
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "SupplServiceEvent" )
    public class SupplServiceEvent implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "SupplServiceEvent" , isSet = false )
       public static class SupplServiceEventSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "chargeableSubscriber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ChargeableSubscriber chargeableSubscriber = null;
                
  
        @ASN1Element ( name = "rapFileSequenceNumber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private RapFileSequenceNumber rapFileSequenceNumber = null;
                
  
        @ASN1Element ( name = "locationInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private LocationInformation locationInformation = null;
                
  
        @ASN1Element ( name = "equipmentIdentifier", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ImeiOrEsn equipmentIdentifier = null;
                
  
        @ASN1Element ( name = "supplServiceUsed", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private SupplServiceUsed supplServiceUsed = null;
                
  
        @ASN1Element ( name = "operatorSpecInformation", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private OperatorSpecInfoList operatorSpecInformation = null;
                
  
        
        public ChargeableSubscriber getChargeableSubscriber () {
            return this.chargeableSubscriber;
        }

        
        public boolean isChargeableSubscriberPresent () {
            return this.chargeableSubscriber != null;
        }
        

        public void setChargeableSubscriber (ChargeableSubscriber value) {
            this.chargeableSubscriber = value;
        }
        
  
        
        public RapFileSequenceNumber getRapFileSequenceNumber () {
            return this.rapFileSequenceNumber;
        }

        
        public boolean isRapFileSequenceNumberPresent () {
            return this.rapFileSequenceNumber != null;
        }
        

        public void setRapFileSequenceNumber (RapFileSequenceNumber value) {
            this.rapFileSequenceNumber = value;
        }
        
  
        
        public LocationInformation getLocationInformation () {
            return this.locationInformation;
        }

        
        public boolean isLocationInformationPresent () {
            return this.locationInformation != null;
        }
        

        public void setLocationInformation (LocationInformation value) {
            this.locationInformation = value;
        }
        
  
        
        public ImeiOrEsn getEquipmentIdentifier () {
            return this.equipmentIdentifier;
        }

        
        public boolean isEquipmentIdentifierPresent () {
            return this.equipmentIdentifier != null;
        }
        

        public void setEquipmentIdentifier (ImeiOrEsn value) {
            this.equipmentIdentifier = value;
        }
        
  
        
        public SupplServiceUsed getSupplServiceUsed () {
            return this.supplServiceUsed;
        }

        
        public boolean isSupplServiceUsedPresent () {
            return this.supplServiceUsed != null;
        }
        

        public void setSupplServiceUsed (SupplServiceUsed value) {
            this.supplServiceUsed = value;
        }
        
  
        
        public OperatorSpecInfoList getOperatorSpecInformation () {
            return this.operatorSpecInformation;
        }

        
        public boolean isOperatorSpecInformationPresent () {
            return this.operatorSpecInformation != null;
        }
        

        public void setOperatorSpecInformation (OperatorSpecInfoList value) {
            this.operatorSpecInformation = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_SupplServiceEventSequenceType;
        }

       private static IASN1PreparedElementData preparedData_SupplServiceEventSequenceType = CoderFactory.getInstance().newPreparedElementData(SupplServiceEventSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "SupplServiceEvent", isOptional =  false , hasTag =  true, tag = 11, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private SupplServiceEventSequenceType  value;        

        
        
        public SupplServiceEvent () {
        }
        
        
        
        public void setValue(SupplServiceEventSequenceType value) {
            this.value = value;
        }
        
        
        
        public SupplServiceEventSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SupplServiceEvent.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            