
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TotalDiscountRefund" )
    public class TotalDiscountRefund implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "TotalDiscountRefund", isOptional =  false , hasTag =  true, tag = 354, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private AbsoluteAmount  value;        

        
        
        public TotalDiscountRefund () {
        }
        
        
        
        public void setValue(AbsoluteAmount value) {
            this.value = value;
        }
        
        
        
        public AbsoluteAmount getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TotalDiscountRefund.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            