
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TrackingCustomerIdentification" )
    public class TrackingCustomerIdentification implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "TrackingCustomerIdentification" , isSet = false )
       public static class TrackingCustomerIdentificationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "customerIdType", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CustomerIdType customerIdType = null;
                
  
        @ASN1Element ( name = "customerIdentifier", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CustomerIdentifier customerIdentifier = null;
                
  
        
        public CustomerIdType getCustomerIdType () {
            return this.customerIdType;
        }

        
        public boolean isCustomerIdTypePresent () {
            return this.customerIdType != null;
        }
        

        public void setCustomerIdType (CustomerIdType value) {
            this.customerIdType = value;
        }
        
  
        
        public CustomerIdentifier getCustomerIdentifier () {
            return this.customerIdentifier;
        }

        
        public boolean isCustomerIdentifierPresent () {
            return this.customerIdentifier != null;
        }
        

        public void setCustomerIdentifier (CustomerIdentifier value) {
            this.customerIdentifier = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_TrackingCustomerIdentificationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_TrackingCustomerIdentificationSequenceType = CoderFactory.getInstance().newPreparedElementData(TrackingCustomerIdentificationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "TrackingCustomerIdentification", isOptional =  false , hasTag =  true, tag = 362, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private TrackingCustomerIdentificationSequenceType  value;        

        
        
        public TrackingCustomerIdentification () {
        }
        
        
        
        public void setValue(TrackingCustomerIdentificationSequenceType value) {
            this.value = value;
        }
        
        
        
        public TrackingCustomerIdentificationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TrackingCustomerIdentification.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            