
package el.data.asn311;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TrackedCustomerEquipment" )
    public class TrackedCustomerEquipment implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "TrackedCustomerEquipment" , isSet = false )
       public static class TrackedCustomerEquipmentSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "equipmentIdType", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private EquipmentIdType equipmentIdType = null;
                
  
        @ASN1Element ( name = "equipmentId", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private EquipmentId equipmentId = null;
                
  
        
        public EquipmentIdType getEquipmentIdType () {
            return this.equipmentIdType;
        }

        
        public boolean isEquipmentIdTypePresent () {
            return this.equipmentIdType != null;
        }
        

        public void setEquipmentIdType (EquipmentIdType value) {
            this.equipmentIdType = value;
        }
        
  
        
        public EquipmentId getEquipmentId () {
            return this.equipmentId;
        }

        
        public boolean isEquipmentIdPresent () {
            return this.equipmentId != null;
        }
        

        public void setEquipmentId (EquipmentId value) {
            this.equipmentId = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_TrackedCustomerEquipmentSequenceType;
        }

       private static IASN1PreparedElementData preparedData_TrackedCustomerEquipmentSequenceType = CoderFactory.getInstance().newPreparedElementData(TrackedCustomerEquipmentSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "TrackedCustomerEquipment", isOptional =  false , hasTag =  true, tag = 381, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private TrackedCustomerEquipmentSequenceType  value;        

        
        
        public TrackedCustomerEquipment () {
        }
        
        
        
        public void setValue(TrackedCustomerEquipmentSequenceType value) {
            this.value = value;
        }
        
        
        
        public TrackedCustomerEquipmentSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TrackedCustomerEquipment.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            